#
# Module manifest for module 'BestPractices'
#
# Generated by: Microsoft Corporation
#
# Generated on: 10/22/2008
#

@{

# These modules will be processed when the module manifest is loaded.
NestedModules = 'Provider.dll'

# This GUID is used to uniquely identify this module.
GUID = [guid]::NewGuid()

# The author of this module.
Author = 'Adam Flax'

# The company or vendor for this module.
CompanyName = 'Huddle'

# The copyright statement for this module.
Copyright = 'Huddle. All rights reserved.'

# The version of this module.
ModuleVersion = '1.0'

# A description of this module.
Description = 'Huddles Custom Provider'

# The minimum version of PowerShell needed to use this module.
PowerShellVersion = '2.0'

# The CLR version required to use this module.
CLRVersion = '2.0'

# This is a list of other modules that this module depends on.
RequiredModules = @()

# The type files (.ps1xml) loaded by this module.
TypesToProcess = @()

# The format files (.ps1xml) loaded by this module.
FormatsToProcess = 'Provider.Format.ps1xml'

# A list of assemblies that must be loaded before this module can work.
RequiredAssemblies = @()

# Lists additional items like icons, etc. that the module will use.
FileList = @()

# Module specific private data can be passed via this member.
PrivateData = ''

}

